global:
  scrape_interval: 1m

scrape_configs:
  - job_name: taskmanager
    static_configs:
      - targets: [ 'taskmanager:9249' ]

  - job_name: jobmanager
    static_configs:
      - targets: [ 'jobmanager:9249' ]